[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "total_perspective_vortex"
version = "0.1.0"
description = "Craft a BCI (Brain-Computer Interface) that can read your mind and predict your next move."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mne",
    "scikit-learn",
    "scipy",
    "matplotlib"
]

[tool.setuptools]
# Explicitly tells setuptools where to look for the packages
package-dir = {"" = "srcs"}

[tool.setuptools.packages.find]
# Automatically finds all packages inside the specified directory
where = ["srcs"]